# Generated by Django 2.1.15 on 2021-06-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_answerlike_questionlike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='like',
        ),
        migrations.AddField(
            model_name='question',
            name='rating',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
