# Generated by Django 2.1.15 on 2021-06-12 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210611_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='title',
            new_name='question',
        ),
    ]
