# Generated by Django 2.1.15 on 2021-06-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210613_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='unnamed.jpg', upload_to='upload/'),
        ),
    ]
