# Generated by Django 2.1.15 on 2021-06-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210613_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='like',
            new_name='rating',
        ),
    ]
